# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loginFirebaseAula21-09' do

pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for loginFirebaseAula21-09

  target 'loginFirebaseAula21-09Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'loginFirebaseAula21-09UITests' do
    # Pods for testing
  end

end
